name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build
    strategy:
      matrix:
        go_version:
          - 1.19.2
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}

    - name: Setup buf action
      uses: bufbuild/buf-setup-action@v1
      with:
        github_token: ${{ github.token }}

    - name: Check out code
      uses: actions/checkout@v3

    - name: Get tools dependencies
      run: make tools

    - name: Build
      run: make build

    - name: Stack
      run: docker-compose -f build/docker/docker-compose.yml up --build -d

    - name: Test
      run: go test -tags integration -race -coverprofile=coverage.txt -covermode=atomic -v ./server/rpc/server_test.go
